version: '3.8'

services:
  crypto-trader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: crypto-ai-trader
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../logs:/app/logs
      - ../.env:/app/.env
    ports:
      - "8000:8000"  # API порт
    depends_on:
      - redis
      - postgres
    networks:
      - crypto-trader-net
    command: ["python", "main.py", "--mode", "both"]

  redis:
    image: redis:7-alpine
    container_name: crypto-trader-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - crypto-trader-net
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    container_name: crypto-trader-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_trader
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crypto-trader-net

  nginx:
    image: nginx:alpine
    container_name: crypto-trader-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - crypto-trader
    networks:
      - crypto-trader-net

volumes:
  redis-data:
  postgres-data:

networks:
  crypto-trader-net:
    driver: bridge